import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PICTURE GALLARY",
  description: "Generated by C.Faiza",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black text-white">
      <body className={inter.className}>
        <Navbar />
        <div className="flex">
          <div className="w-1/5">
            <Sidebar />
          </div>
          <div className="w-full px-4 py-2 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
